### ISSUE TITLE
conntrack

### ISSUE THREAD

**Issue by ToterEngel** [Enkidu-6/tor-ddos#38]
I tested the Conntrack script for a while, but the output is distorted.

Because it also lists my own IPv4 with currently ~4400 counters.

Therefore, the local IP would have to be excluded from the calculation somehow.

**Comment by Enkidu-6** [comment]
That's not a flaw, it's a feature. It shows the current number of your established connections on both your IPV4 and IPV6 addresses. It's also an indication of how many of your local ports are not available for new connections. 

On a system with very high traffic it could also serve as a warning sign showing how close you might be to running out of local ports.

**Comment by ToterEngel** [comment]
OK, I must have misinterpreted this then.

At least I still have enough reserves for the ports.


Conntrack count:
 20151
Two connections, Relays:
 There are 2331 IPs with two connections 1524 of which are Relays
Two connections, dual-or:
 There are 2331 IPs with two connections 129 of which are Dual-OR Relays
One connection, Relays:
 There are 7613 IPs with one connection 1788 of which are Relays
One connection, dual-or:
 There are 7613 IPs with one connection 183 of which are Dual-OR Relays
