### ISSUE TITLE
No hits on iptables rules?

### ISSUE THREAD

**Issue by cybermonkee** [Enkidu-6/tor-ddos#53]
I am wondering if this is right - or if it is just me? No pkts or bytes on any of the iptables rules including the accept.

Chain PREROUTING (policy ACCEPT 0 packets, 0 bytes)
num   pkts bytes target     prot opt in     out     source               destination
1        0     0 ACCEPT     tcp  --  any    any     anywhere             193.38.255.253       tcp dpt:https match-set allowed-relays src
2        0     0 ACCEPT     tcp  --  any    any     anywhere             193.38.255.253       tcp dpt:9001 match-set allowed-relays src
3        0     0 ACCEPT     tcp  --  any    any     anywhere             193.38.255.253       tcp dpt:https match-set allow-list src
4        0     0 ACCEPT     tcp  --  any    any     anywhere             193.38.255.253       tcp dpt:9001 match-set allow-list src
5        0     0            tcp  --  any    any     anywhere             193.38.255.253       tcp dpt:9001 recent: SET name: ddos-193.38.255.253-9001 side: source mask: 255.255.255.255
6        0     0 SET        tcp  --  any    any     anywhere             193.38.255.253       tcp dpt:9001 #conn src/32 > 2 add-set tor-193.38.255.253-9001 src
7        0     0 DROP       tcp  --  any    any     anywhere             193.38.255.253       match-set tor-193.38.255.253-9001 src
8        0     0 DROP       tcp  --  any    any     anywhere             193.38.255.253       tcp dpt:9001 flags:FIN,SYN,RST,ACK/SYN ctstate NEW limit: above 30/hour burst 2 mode srcip htable-expire 120000
9        0     0 DROP       tcp  --  any    any     anywhere             193.38.255.253       tcp dpt:9001 flags:FIN,SYN,RST,ACK/SYN #conn src/32 > 2
10       0     0 ACCEPT     tcp  --  any    any     anywhere             193.38.255.253       tcp dpt:9001
11       0     0            tcp  --  any    any     anywhere             193.38.255.253       tcp dpt:https recent: SET name: ddos-193.38.255.253-443 side: source mask: 255.255.255.255
12       0     0 SET        tcp  --  any    any     anywhere             193.38.255.253       tcp dpt:https #conn src/32 > 2 add-set tor-193.38.255.253-443 src
13       0     0 DROP       tcp  --  any    any     anywhere             193.38.255.253       match-set tor-193.38.255.253-443 src
14       0     0 DROP       tcp  --  any    any     anywhere             193.38.255.253       tcp dpt:https flags:FIN,SYN,RST,ACK/SYN ctstate NEW limit: above 30/hour burst 2 mode srcip htable-expire 120000
15       0     0 DROP       tcp  --  any    any     anywhere             193.38.255.253       tcp dpt:https flags:FIN,SYN,RST,ACK/SYN #conn src/32 > 2
16       0     0 ACCEPT     tcp  --  any    any     anywhere             193.38.255.253       tcp dpt:https

Chain INPUT (policy ACCEPT 0 packets, 0 bytes)
num   pkts bytes target     prot opt in     out     source               destination

Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
num   pkts bytes target     prot opt in     out     source               destination

Chain OUTPUT (policy ACCEPT 0 packets, 0 bytes)
num   pkts bytes target     prot opt in     out     source               destination

Chain POSTROUTING (policy ACCEPT 0 packets, 0 bytes)
num   pkts bytes target     prot opt in     out     source               destination

**Comment by Enkidu-6** [comment]
Hi,

Mine shows packets and bytes just fine. Are you doing iptables -Lv -t mangle?

By the way the hashlimit burst should be 4. Yours show 2. Use the newest version of update.sh to change that to the new value.

**Comment by cybermonkee** [comment]
> 

root@onion-router:~**# iptables -L -v -t mangle**
Chain PREROUTING (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination
    0     0 ACCEPT     tcp  --  any    any     anywhere             193.38.255.253       tcp dpt:https match-set allow-list src
    0     0 ACCEPT     tcp  --  any    any     anywhere             193.38.255.253       tcp dpt:9001 match-set allow-list src
    0     0            tcp  --  any    any     anywhere             193.38.255.253       tcp dpt:9001 recent: SET name: ddos-193.38.255.253-9001 side: source mask: 255.255.255.255
    0     0 SET        tcp  --  any    any     anywhere             193.38.255.253       tcp dpt:9001 #conn src/32 > 2 add-set tor-193.38.255.253-9001 src
    0     0 DROP       tcp  --  any    any     anywhere             193.38.255.253       match-set tor-193.38.255.253-9001 src
    0     0 DROP       tcp  --  any    any     anywhere             193.38.255.253       tcp dpt:9001 flags:FIN,SYN,RST,ACK/SYN limit: above 30/hour burst 4 mode srcip htable-expire 120000
    0     0 DROP       tcp  --  any    any     anywhere             193.38.255.253       tcp dpt:9001 flags:FIN,SYN,RST,ACK/SYN #conn src/32 > 2
    0     0 ACCEPT     tcp  --  any    any     anywhere             193.38.255.253       tcp dpt:9001
    0     0            tcp  --  any    any     anywhere             193.38.255.253       tcp dpt:https recent: SET name: ddos-193.38.255.253-443 side: source mask: 255.255.255.255
    0     0 SET        tcp  --  any    any     anywhere             193.38.255.253       tcp dpt:https #conn src/32 > 2 add-set tor-193.38.255.253-443 src
    0     0 DROP       tcp  --  any    any     anywhere             193.38.255.253       match-set tor-193.38.255.253-443 src
    0     0 DROP       tcp  --  any    any     anywhere             193.38.255.253       tcp dpt:https flags:FIN,SYN,RST,ACK/SYN limit: above 30/hour burst 4 mode srcip htable-expire 120000
    0     0 DROP       tcp  --  any    any     anywhere             193.38.255.253       tcp dpt:https flags:FIN,SYN,RST,ACK/SYN #conn src/32 > 2
    0     0 ACCEPT     tcp  --  any    any     anywhere             193.38.255.253       tcp dpt:https

Chain INPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain OUTPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain POSTROUTING (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination

**Comment by cybermonkee** [comment]
Doh - fixed it... just realised this is a natted address... sigh... I need more coffee...

**Comment by Enkidu-6** [comment]
Sounds good. Just remember to use the update.sh . It removes the --ctstate and increases the hashlimit burst. The update file will keep your current block list entries.
