### ISSUE TITLE
Errors when applying iptables rules

### ISSUE THREAD

**Issue by concpt** [Enkidu-6/tor-ddos#73]
I followed the guide of providing the IP and Port of Tor, and then I ran multi.sh and the rules did not apply, and I was left with a bunch of errors.

I'm using Debian 11

>iptables v1.8.7 (nf_tables): option "--destination" requires an argument
Try `iptables -h' or 'iptables --help' for more information.
iptables v1.8.7 (nf_tables): option "--destination" requires an argument
Try `iptables -h' or 'iptables --help' for more information.
iptables v1.8.7 (nf_tables): option "--destination" requires an argument
Try `iptables -h' or 'iptables --help' for more information.
iptables v1.8.7 (nf_tables): option "--destination" requires an argument
Try `iptables -h' or 'iptables --help' for more information.
iptables v1.8.7 (nf_tables): option "--destination" requires an argument
Try `iptables -h' or 'iptables --help' for more information.
iptables v1.8.7 (nf_tables): option "--destination" requires an argument
Try `iptables -h' or 'iptables --help' for more information.
iptables v1.8.7 (nf_tables): option "--destination" requires an argument
Try `iptables -h' or 'iptables --help' for more information.
iptables v1.8.7 (nf_tables): option "--destination" requires an argument
Try `iptables -h' or 'iptables --help' for more information.
iptables v1.8.7 (nf_tables): host/network `This' not found
Try `iptables -h' or 'iptables --help' for more information.
iptables v1.8.7 (nf_tables): host/network `This' not found
Try `iptables -h' or 'iptables --help' for more information.
iptables v1.8.7 (nf_tables): host/network `This' not found
Try `iptables -h' or 'iptables --help' for more information.
iptables v1.8.7 (nf_tables): host/network `This' not found
Try `iptables -h' or 'iptables --help' for more information.
iptables v1.8.7 (nf_tables): host/network `This' not found
Try `iptables -h' or 'iptables --help' for more information.
iptables v1.8.7 (nf_tables): host/network `This' not found
Try `iptables -h' or 'iptables --help' for more information.
iptables v1.8.7 (nf_tables): host/network `This' not found
Try `iptables -h' or 'iptables --help' for more information.
iptables v1.8.7 (nf_tables): host/network `This' not found
Try `iptables -h' or 'iptables --help' for more information.
iptables v1.8.7 (nf_tables): invalid port/service `-m' specified
Try `iptables -h' or 'iptables --help' for more information.
iptables v1.8.7 (nf_tables): invalid port/service `-m' specified
Try `iptables -h' or 'iptables --help' for more information.
iptables v1.8.7 (nf_tables): invalid port/service `-m' specified
Try `iptables -h' or 'iptables --help' for more information.
iptables v1.8.7 (nf_tables): invalid port/service `-m' specified
Try `iptables -h' or 'iptables --help' for more information.
iptables v1.8.7 (nf_tables): invalid port/service `-m' specified

**Comment by Enkidu-6** [comment]
It seems that the script can't find your IP addresses and ports which means either ipv4.txt and ipv6.txt don't exist or they're not in the same directory as multi.sh directory or the format of the ipaddress port entries is not correct. 

Look inside the file rules.sh and if you don't see your ip address in any of those lines,  that's probably the case.

**Comment by concpt** [comment]
Oh my bad, I see what happened now. I didn't remove the comment at the top

**Comment by Enkidu-6** [comment]
Feel free to reach out if you have any problems.
