### ISSUE TITLE
Crontab for refresh-authorities.sh

### ISSUE THREAD

**Issue by PacaAlpaca** [Enkidu-6/tor-ddos#80]
Hi, when I use commands from your instruction:

`(crontab -l ; echo "0 0 * * * /$PWD/refresh-authorities.sh") | crontab -`

I get output:

![obraz](https://user-images.githubusercontent.com/112646966/219884511-88b70fc9-f395-4aa0-a677-3dbd2a285675.png)

`root@xxxxx:/home/xxxxx# (crontab -l ; echo "22 2 * * * /$PWD/refresh-authorities.sh") | crontab -`
`no crontab for root`
`root@xxxxx:/home/xxxxx# crontab -l`
`22 2 * * * //home/xxxxx/refresh-authorities.sh`

I think there is a problem with double slash "22 2 * * * **/**/home/xxxxx/refresh-authorities.sh" becouse command $PWD give you path with / at the beginnig and your command start with another slash before it: **/**$PWD

I am not 100% sure it is wrong but i think it will not work in this form.

Used on: Debian 11

**Comment by Enkidu-6** [comment]
You are indeed correct. There's a typo there with the extra / . Thanks for catching it. It's been corrected.

**Comment by Enkidu-6** [comment]
I also made an announcement in the discussion forum so people can double check their crontab and make sure it's working correctly:

https://github.com/Enkidu-6/tor-ddos/discussions/83

Thanks again
