### ISSUE TITLE
Add check before removing files when they do not exist

### ISSUE THREAD

**Issue by PacaAlpaca** [Enkidu-6/tor-ddos#93]
In start.sh, [line 68](https://github.com/Enkidu-6/tor-ddos/blob/main/start.sh#L68), file ipv4.txt is removed but if there is no file ("new installation" etc.) it throws an error to user which can couse confusion.
Same in line 80 for ipv6.txt.

![obraz](https://github.com/Enkidu-6/tor-ddos/assets/112646966/e35cc86c-79b3-40a5-b200-1a99a8410981)

Maybe it is possible to add check and try to remove file only if exists, like:
```
if [[ -f "ipv4.txt" ]]; then
  /bin/rm -r ipv4.txt
fi
```

**Comment by Enkidu-6** [comment]
Thank you for your input. You're correct and I'll implement your suggestion shortly.
Cheers.
